<a href="https://colab.research.google.com/github/sainikhilgb/Python4DS/blob/master/Copy_of_Assignment1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment

Import numpy as np

In [ ]:
import numpy as np


Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [ ]:
list = [1,2,3,4,5]
print(np.array(list))

[1 2 3 4 5]


Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [ ]:

arr= np.arange(1,10).reshape(3,3)
arr1=arr.flatten()
arr1



array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [ ]:
a= np.arange(1,18,2).reshape(3,3)
a

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])


Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [ ]:
import random
arry= np.random.rand(10)
arry

array([0.19056251, 0.04066625, 0.33393275, 0.59193954, 0.27405129,
       0.61167881, 0.77679805, 0.19150018, 0.50567281, 0.99480014])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [ ]:
array = [1,2,3,4,5]
arr=np.reshape(array,(5,1))
arr


array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [ ]:
arr.shape

(3, 3)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [ ]:
a=np.arange(10)
print(a[3],a[4],a[9])

3 4 9


Print alternate elements of that array

In [ ]:
arr2=np.arange(1,10,2)
arr2

array([1, 3, 5, 7, 9])

Change last 3 elements into 100 using broadcasting and print

NameError: ignored

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [ ]:
a=np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])